### ISSUE TITLE
Documentation for stacks doesn't have the respective classname

### ISSUE THREAD

**Issue by vipuldialpad** [dialpad/dialtone#116]
The various stacks in the examples should have classnames for the stack size being documented.

Currently, they all look the same.
<img width="718" alt="dialtone-stacks" src="https://user-images.githubusercontent.com/67323341/93622993-a9da8780-f9fb-11ea-93c0-cf3ca9fa34ea.png">

**Comment by tedgoas-dialpad** [comment]
@vikdialpad was this fixed in #117?

**Comment by vikdialpad** [comment]
@TedGoas not sure what this is. did u mean to tag someone else ?

**Comment by tedgoas-dialpad** [comment]
@vikdialpad Oops, yes sorry!

**Comment by tedgoas-dialpad** [comment]
@vipuldialpad was this fixed in #117?

**Comment by vipuldialpad** [comment]
@TedGoas yes, indeed!
