### ISSUE TITLE
Component: Toast

### ISSUE THREAD

**Issue by natayi-dialpad** [dialpad/dialtone#120]
<img width="583" alt="Screen Shot 2020-09-24 at 1 04 30 PM" src="https://user-images.githubusercontent.com/70347894/94195981-92baf000-fe68-11ea-8b81-590be544ceb5.png">
<img width="672" alt="Screen Shot 2020-09-24 at 1 04 37 PM" src="https://user-images.githubusercontent.com/70347894/94195985-9484b380-fe68-11ea-89d1-78bbedc00dfe.png">
<img width="927" alt="Screen Shot 2020-09-24 at 1 19 15 PM" src="https://user-images.githubusercontent.com/70347894/94196141-cac23300-fe68-11ea-9f8d-b42feca457a3.png">

**Comment by hynes-dialpad** [comment]
@dbecherdialpad The CSS styles for notices are finished, but I have not applied them to toasts yet. I'll handle that in a PR next.
