### ISSUE TITLE
Add a new right arrow icon

### ISSUE THREAD

**Issue by linlidialpad** [dialpad/dialtone#125]
In the new integration setting project, we have [a feature to make a panel expand and collapse](https://switchcomm.atlassian.net/browse/DP-29811), so we would like to add a new right arrow icon to be used to together with the existing IconArrowDropDown. 

Here's the design from Polly Lee and she has provided me the svg file for the new right arrow icon. 

![Screen Shot 2020-09-18 at 11 19 19 AM](https://user-images.githubusercontent.com/57730092/94968239-6bda6a80-04b5-11eb-9630-8cc847f48464.png)

**Comment by linlidialpad** [comment]
^ @dbecherdialpad @tedgoas-dialpad 
Not sure what's the right process here, I guess I need your approval before submitting the PR?

**Comment by tedgoas-dialpad** [comment]
@linlidialpad Generally myself, Josh, or David review / approve. I'll add us all, thanks for the PR!

**Comment by tedgoas-dialpad** [comment]
@linlidialpad Or I guess you have to do that since it's your PR?

**Comment by linlidialpad** [comment]
@tedgoas-dialpad yep, I will submit the PR soon. Btw, can you grant me write permission to this repo? I cannot push a remote branch at the moment. Thanks!
