### ISSUE TITLE
Add new icons for Video recording in UC

### ISSUE THREAD

**Issue by alekseyh5** [dialpad/dialtone#160]
The new icons are collected on [this Figma page](https://www.figma.com/file/jy2fIaUsLtY6KI0OulQujL/UC-254-Video-Recording?node-id=316%3A0).

Essentially there is one new custom icon. In the UI there's a variation of this icon with a red dot. Please use your best judgment to decide whether to add a variation as a separate dialtone component. Alternatively, in Figma, I provided guidance for implementing the multi-color variation based on the monochrome one.

**Comment by hynes-dialpad** [comment]
@alekseyh5 Can you place this icon in the Dialtone Icons file?

**Comment by alekseyh5** [comment]
I placed the new icon (monochrome version) there. The Figma page that I mentioned in the description of the request still needs your attention. TBD is the implementation method of the multi-color variation of the icon.

**Comment by hynes-dialpad** [comment]
@dialpad-drew Another icon we should include in the next Dialtone version.

**Comment by dialpad-drew** [comment]
> I placed the new icon (monochrome version) there. The Figma page that I mentioned in the description of the request still needs your attention. TBD is the implementation method of the multi-color variation of the icon.

Hey @alekseyh5 , I'm looking at your Figma link and am not totally following what needs attention here. Are there two versions of this icon: one for starting a recording and another (with the red dot and border) for a recording in progress?
