### ISSUE TITLE
Add new icons for Live Vi in UC

### ISSUE THREAD

**Issue by alekseyh5** [dialpad/dialtone#161]
The icons are collected on [this Figma page](https://www.figma.com/file/Hv7IsD633ZtWPHSnUcmh6j/Live-VI-in-UC?node-id=886%3A0)

**Comment by hynes-dialpad** [comment]
@alekseyh5 A few things:

 1. Please move these icons over to the correct Dialtone Figma Icons file so I can export them there. I don't want to have multiple icon files.
 2. Why do we need a circle check and then one with a plus?
 3. The notes icon is a bit nondescript. Also @tedgoas-dialpad recently introduced a "Grade" icon which is similar. Can we differentiate this icon a bit more?

![image](https://user-images.githubusercontent.com/44445385/106333060-ef367d80-6255-11eb-844c-72d23d45159d.png)

**Comment by alekseyh5** [comment]
1. Done
2. Explained it in [this video](https://www.loom.com/share/3eecb167c3134789bd46f1b7dc704a1a) (watch from 1:40). [Figma board](https://www.figma.com/file/Hv7IsD633ZtWPHSnUcmh6j/Live-VI-in-UC?node-id=884%3A9060).
3. These 2 icons co-exist in Material library. They are different enough to co-exist in our products also I think.

**Comment by hynes-dialpad** [comment]
@dialpad-drew Another icon we should include in the next Dialtone version.
