### ISSUE TITLE
[CSS] Component: Inputs

### ISSUE THREAD

**Issue by ryandialpad** [dialpad/dialtone#219]
**Acceptance Criteria**

- Update the input component Dialtone classes

**Resources**

Design: https://www.figma.com/file/zP2uyVxAg4notGNZwW64mW/Components-(Dialtone-6.0)?node-id=39%3A3022

**Comment by dialpad-drew** [comment]
This particular documentation will need a little clean-up:

Right now, on the Dialtone site, Text Inputs and Textareas are different pages and shown as separate components. In this 6.0 redesign (linked above), I re-built the Figma symbol to better match the Vue architecture (i.e. it’s all in an Inputs component).

So, we'll need to merge the Textarea documentation into the Inputs documentation so its organization matches.
