### ISSUE TITLE
Add color hex's to documentation

### ISSUE THREAD

**Issue by rehandialpad** [dialpad/dialtone#22]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/33042378/64190810-02100d00-ce2c-11e9-9542-169090a891c4.png">

For the background color samples in the documentation if would be useful to display the corresponding hex or rgba string next to the class name, so we can at a glance tell which color the design is using. 

I know this can be mitigated by inspecting the element in the browser debug tools, but having the hex string would save a lot of time, and quickly let us know if the designer is using a color that is out of our design spec.

https://dialpad.design/utilities/visual/backgrounds/

**Comment by tedgoas-dialpad** [comment]
Looks like this one got addressed sometime in the last 11 months, closing for now.
