### ISSUE TITLE
[CSS] Component: Radios

### ISSUE THREAD

**Issue by ryandialpad** [dialpad/dialtone#220]
**Acceptance Criteria**

- Update the radio component Dialtone classes

**Resources**

Design: https://www.figma.com/file/zP2uyVxAg4notGNZwW64mW/Components-(Dialtone-6.0)?node-id=3845%3A7529

**Comment by dialpad-drew** [comment]
BTW, take a look at #196 . It's what you sent me last week.

**Comment by dialpad-drew** [comment]
Resolved by #224
