### ISSUE TITLE
Do we want to use "em" for --base--corner-radius?

### ISSUE THREAD

**Issue by dialpad-drew** [dialpad/dialtone#297]
The `--base--corner-radius` var defined in `themes/default.less` has as value of `0.25em`. Being that it's `em`, when applied to elements with differing font sizes, obviously the border-radius will also differ from element to element. Do we want the global border radius to be dynamic and relative to a parent font-size, or do we want it to be more of a static value?

As an example, let's say we applied this var to buttons:

Button Size | Font Size | Computed Border Radius
------------ | ------------- | -------------
Extra Small | 12px | 3px
Small | 14px | 3.5px
Medium | 16px | 4px
Large | 20px | 5px
Extra Large | 24px | 6px

![Screen Shot 2021-04-27 at 3 28 48 PM](https://user-images.githubusercontent.com/77751297/116315105-4b357300-a76d-11eb-8281-1c3d6e8840a8.png)

I could definitely see value in this type of dynamic approach in certain circumstances, but I want to learn more about the use cases.

**Comment by dialpad-drew** [comment]
We should use this consistently as we do in DT5. The problem here isn't the variability, it's the inconsistent applies in our DT6 CSS, so we end up with things like this:

![Screen Shot 2021-04-27 at 3 36 26 PM](https://user-images.githubusercontent.com/77751297/116315858-58069680-a76e-11eb-9f5c-981773c0059a.png)

**Comment by hynes-dialpad** [comment]
Is this an issue @dialpad-drew? Happy to share my reasoning 😄

**Comment by dialpad-drew** [comment]
> Is this an issue @dialpad-drew? Happy to share my reasoning 😄

No, I don't think it is. This is a case of "ready-fire-aim" by me. I didn't think through what I was actually trying to solve for before making this. 🤦
