### ISSUE TITLE
Update our DP and DiPaMe icons in Dialtone

### ISSUE THREAD

**Issue by vcheng-dialpad** [dialpad/dialtone#358]
Could someone help me update our Dialpad & Dialpad Meetings logo? 

In [Figma](https://www.figma.com/file/FHMdVqC8qWcEn9Ox1s6k2e/Icons?node-id=0%3A1),  I've created new icons above our existing ones for reference. 

![image](https://user-images.githubusercontent.com/67069882/124045659-fb6d6500-d9c4-11eb-89ec-d63d3723f7a9.png)

![image(https://media.giphy.com/media/26gsjCZpPolPr3sBy/giphy.gif)

**Comment by hynes-dialpad** [comment]
I'm not sure we should replace the UC glyph with the DP Meetings glyph. We aren't going to swap out the UC glyph for the DP Meetings glyph in the product. We're replacing it with a video icon.

**Comment by dialpad-drew** [comment]
Thanks for this, @vcheng-dialpad !

@hynes-dialpad , in the case we don't want to shim or replace the UC icon to the DPM icon in the library, I'm thinking we have two options:

1. Keep the UC brand icon for the time-being and document it as deprecated
2. Remove it altogether 

In either case, we'll add DPM's brand icon as a net new icon. I'm inclined to go with the first option and include the breaking change of asset removal in DT6.
