### ISSUE TITLE
d-m-auto class on dialtone missing another '-'

### ISSUE THREAD

**Issue by sanjeevdialpad** [dialpad/dialtone#365]
The auto margin section in dialtone:
<img width="629" alt="Screenshot 2021-07-14 at 3 03 28 PM" src="https://user-images.githubusercontent.com/49391671/125599448-9dc9e9be-fdb5-43b4-81c0-9fcd1f53a088.png">

`d-m-auto` should be `d-m--auto`

at the same time all other classes are correct:
`d-mr-auto` `d-mx-auto` ...

**Comment by dialpad-drew** [comment]
This is now fixed [in the documentation](https://dialpad.design/utilities/layout/margin/), @sanjeevdialpad . Thanks again!
