### ISSUE TITLE
Raise/Lower hand Icon needed in Uberconference

### ISSUE THREAD

**Issue by hectordialpad** [dialpad/dialtone#383]
We need an icon for raise/lower hand action during meetings in Uberconference. The proposed icon is back hand, and it does not appear to be on available icons.

https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aback_hand

Can I make a PR to add it to dialtone?

**Comment by dialpad-drew** [comment]
Hey @hectordialpad, that would be great. Will you PR it into both Dialtone 5.0 and 6.0, or do you want me to handle 6.0?

**Comment by dialpad-drew** [comment]
Also, which designer are you working with on this?

**Comment by hectordialpad** [comment]
We are


> Also, which designer are you working with on this?



> Hey @hectordialpad, that would be great. Will you PR it into both Dialtone 5.0 and 6.0, or do you want me to handle 6.0?

Are those branches in the repo? I can do that.

> Also, which designer are you working with on this?

We are working with Aleksey LIashevsky, I do not know git Github username

**Comment by dialpad-drew** [comment]
> Are those branches in the repo? I can do that.

Perfect! Version 5, which you use now, is on the `staging` branch and version 6, which we're gearing up to release, is on the `version6` branch. The process of adding icons should be the same for both.

**Comment by hectordialpad** [comment]
I don't think I have permission to push remote branches in this repo. Am I supposed to make a Fork?

**Comment by dialpad-drew** [comment]
> I don't think I have permission to push remote branches in this repo. Am I supposed to make a Fork?

Hmmm, it does look like we restrict write access. I'll have to look into that. In the meantime, I'll do the PRs. Sorry about that.
