### ISSUE TITLE
Missing blue text color

### ISSUE THREAD

**Issue by linlidialpad** [dialpad/dialtone#47]
I try to use [text color from Dialtone](https://dialpad.design/utilities/typography/colors/.) when migrating part of the user settings to Vue component, but I didn't find any color that is close to the existing blue color used for link-style buttons (used heavily in the entire settings page). Would be great if Dailtone can add this color or a new button for this link style. See screenshot below. 

![Screen Shot 2019-12-17 at 4 17 30 PM](https://user-images.githubusercontent.com/57730092/71045340-70ca5b00-20e9-11ea-8366-36fc7c798160.png)

Also, it would be helpful to show example with the text color directly in the documentation. like this 
![Screen Shot 2019-12-17 at 4 28 31 PM](https://user-images.githubusercontent.com/57730092/71045617-75434380-20ea-11ea-9bea-f056eb657b68.png)

**Comment by hynes-dialpad** [comment]
As of `v5.8.0`, all colors are now available as font colors. You can view them here: https://dialpad.design/utilities/typography/colors/
