### ISSUE TITLE
h:d-bgc-transparent doesn't exist for 

### ISSUE THREAD

**Issue by tedgoas-dialpad** [dialpad/dialtone#491]
In reading through Dialtone's utility classes, I see that we can prefix any background color with `h:` to apply hover-only styles. However I noticed that `h:d-bgc-transparent` doesn't work (if we want to negate a hover style). **Can we create this?**

There might be other styles that don't have matching hover (`h:`) and focus (`:f`) styles. I didn't do a thorough audit but wanted to make sure I documented this one case before I forgot :)

**Comment by dialpad-drew** [comment]
Thanks for submitting this, @tedgoas-dialpad . We'll look at this. 🙌
