### ISSUE TITLE
Docs error in SVG / Sizes

### ISSUE THREAD

**Issue by tedgoas-dialpad** [dialpad/dialtone#523]
On the [docs page for SVG](https://dialpad.design/utilities/svg/size/) I noticed a bunch of output values not getting output correctly in the docs:

<img width="775" alt="Screen Shot 2021-12-20 at 2 30 52 PM" src="https://user-images.githubusercontent.com/65190890/146822416-844705f4-2336-4c69-9c8c-7c814f13e7e6.png">

**Comment by josedialpad** [comment]
Oops, thanks for reporting @tedgoas-dialpad

**Comment by dialpad-drew** [comment]
Thanks, @tedgoas-dialpad. We're tracking this here: https://switchcomm.atlassian.net/browse/DT-342
