### ISSUE TITLE
Min-Width for badges

### ISSUE THREAD

**Issue by tedgoas-dialpad** [dialpad/dialtone#544]
Wondering if we can give our badges a `min-width`. It looks like we're relying on padding to set width. This gives single-digit numerical counts a different width, which is noticeable when looking at a column of badges (say in an inbox).

![Screen Shot 2022-02-07 at 4 22 46 PM](https://user-images.githubusercontent.com/65190890/152878068-8e232170-8d01-4639-852a-5c6531e4189d.png)

---

Not _technically_ a bug but 🤷‍♀️

**Comment by hynes-dialpad** [comment]
Can we also please visually center the numbers within the badge when implemented? As you can see in the following examples, the numbers sit at an incorrect baseline position within the badge background field.
<img width="48" alt="image" src="https://user-images.githubusercontent.com/44445385/152998990-5f0a9eb8-7ee1-4ed3-8d47-febb8a88e614.png">
<img width="252" alt="image" src="https://user-images.githubusercontent.com/44445385/152999022-36388d6f-b98b-4107-b4c8-e949a07eb917.png">
<img width="674" alt="image" src="https://user-images.githubusercontent.com/44445385/152999052-0c927b28-9603-4ae7-a380-2713ed204934.png">
<img width="119" alt="image" src="https://user-images.githubusercontent.com/44445385/152999087-8c08a8bf-e7c7-4d65-9261-efc2c722f020.png">

Also why are badge counts and the selected tab in the Inbox not bolded?

**Comment by dialpad-drew** [comment]
@braddialpad wanna make sure you saw this -- could be good stuff to groom w/ the team.

**Comment by braddialpad** [comment]
Thanks, added to our backlog
