### ISSUE TITLE
Update Dialtone purple stops

### ISSUE THREAD

**Issue by hynes-dialpad** [dialpad/dialtone#629]
**Request:** The Dialpad Brand Design team recently finalized new purple color stops. This is a request to update these stops.

<img width="842" alt="Visual comparison of updated purple stops and consolidation" src="https://user-images.githubusercontent.com/44445385/179783709-2d8d7454-f0a8-4844-b150-78314a4ce9c6.png">

<table>
  <thead>
    <tr>
      <th align="left" width="15%">Current Stop</th>
      <th align="left" width="5%">New?</th>
      <th align="left" width="15%">Updated Stop</th>
      <th align="left" width="20%">Color Info</th>
      <th align="left" width="30%">Notes</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>--purple-100</code></td>
      <td>No</td>
      <td><code>--purple-100</code></td>
      <td><b>RGB:</b> 238 229 255<br/>#EEE5FF<br/>Passes <b>AAA</b> ✅ 7.81:1</td>
      <td>Minor color adjustment</td></td>
    </tr>
    <tr>
      <td><code>--purple-200</code></td>
      <td>No</td>
      <td><code>--purple-200</code></td>
      <td><b>RGB:</b> 211 188 255<br/>#D3BCFF<br/>Passes <b>AAA</b> ✅ 11.35:1 </td>
      <td>Minor color adjustment. New stop from Brand.</td>
    </tr>
    <tr>
      <td><code>--purple-300</code></td>
      <td>No</td>
      <td><code>--purple-300</code></td>
      <td><b>RGB:</b> 171 126 255<br/>#AB7EFF<br/>Passes <b>AA</b> ⚠️ 6.54:1</td>
      <td>Color brightened. New stop from Brand.</td>
    </tr>
    <tr>
      <td><code>--purple-400</code></td>
      <td>No</td>
      <td><code>--purple-400</code></td>
      <td rowspan="2"><b>RGB:</b> 124 82 255<br/>#7C52FF<br/>Passes <b>AA</b> ⚠️  4.65:1 (White)<br/>Passes <b>AA</b> ⚠️ 4.11:1 (Black)</td>
      <td rowspan="2">This is the new <code>--primary-color</code> purple color stop, given to us by Brand. It desaturates the previous <code>purple-500</code>, allowing us to combine current <code>purple-400</code> & <code>purple-500</code> stops into one updated <code>purple-400</code>.</td>
    </tr>
    <tr>
      <td><code>--purple-500</code></td>
      <td>Yes</td>
      <td><code>--purple-400</code></td>
    </tr>
    <tr>
      <td><code>--purple-600</code></td>
      <td>Yes</td>
      <td><code>--purple-500</code></td>
      <td rowspan="2"><b>RGB:</b> 58 29 149<br/>#3A1D95<br/>Passes <b>AAA</b> ✅ 11.73:1</td>
      <td rowspan="2">New stop from Brand, allowing us to collapse current <code>purple-600</code> & <code>purple-700</code> stops into one updated <code>purple-500</code>.</td>
    </tr>
    <tr>
      <td><code>--purple-700</code></td>
      <td>Yes</td>
      <td><code>--purple-500</code></td>
    </tr>
    <tr>
      <td><code>--purple-800</code></td>
      <td>Yes</td>
      <td><code>--purple-600</code></td>
      <td><b>RGB:</b> 16 2 44<br/>#10022C<br/>Passes <b>AAA</b> ✅ 19.67:1</td>
      <td>New stop from Brand that darken our current <code>purple-800</code>. With the previous 4 stops combining into two stops, this stop number is adjusted to <code>purple-600</code>.</td>
    </tr>
  </tbody>
</table>

The following counts indicate current purple stop usage in key repos:
| Color | `firespotter` | `dialtone` | `dialtone-vue` | Convert to… |
| :-- | --: | --: | --: | :-- |
| `purple-100` | 24 | 4 | 4 | `purple-100` |
| `purple-200` | 2 | 3 | 3 | `purple-200` |
| `purple-300` | 14 | 5 | 6 | `purple-300` |
| `purple-400` | 1 | 2 | 0 | `purple-400` |
| `purple-500` | 64 | 9 | 7 | `purple-400` |
| `purple-600` | 28 | 3 | 3 | `purple-500` |
| `purple-700` | 1 | 5 | 4 | `purple-500` |
| `purple-800` | 16 | 4 | 1 | `purple-600` |

**Comment by dialpad-drew** [comment]
To keep the history clean and up-to-date, Josh and I discussed this in Slack: this is the start of DT7 work that will support this fall's UI update. So, this should actually be merged into a DT7 branch, from which we start cutting pre-release packages.

**Comment by francisrupert** [comment]
Officially tracked in [DT-577](https://dialpad.atlassian.net/browse/DT-577).

**Comment by francisrupert** [comment]
Resolved via PRs https://github.com/dialpad/dialtone/pull/633, https://github.com/dialpad/dialtone/pull/636
