### ISSUE TITLE
Component: Notices

### ISSUE THREAD

**Issue by tedgoas-dialpad** [dialpad/dialtone#73]
We're using Notices in various parts of our product and designs, but I've seen a few different implementations.

![Screen Shot 2020-05-26 at 4 13 08 PM](https://user-images.githubusercontent.com/65190890/82946138-d873b480-9f6b-11ea-83e2-bb350990f8c3.png)
![Screen Shot 2020-06-29 at 4 33 37 PM](https://user-images.githubusercontent.com/65190890/86053323-53763200-ba26-11ea-9ba7-a82126a6d229.png)

Let's codify:
- What they should look like (if there's a style other than what's above)
- Content guidelines (When should icons be used? Are links ok? Can actions be undone?).
- How should they behave (should they appear in the top right corner or be centered? Should they disappear on their own or be dismissed?)?

**Comment by hynes-dialpad** [comment]
Inline notices and banner styles have been addressed in v5.11.0. New toasts styles will be addressed in v5.12 and tracked in issue #120. Closing.
